var services=[
{id:'rkab',name:'RKAB',category:'Perencanaan',desc:'Rencana kerja dan anggaran biaya pertambangan.',image:'rkab.png'},
{id:'reklamasi',name:'E-Reklamasi',category:'Lingkungan',desc:'Rencana reklamasi dan pemulihan lahan.',image:'reklamasi.png'},
{id:'pnbp',name:'PNBP',category:'Penerimaan',desc:'Administrasi penerimaan negara sektor minerba.',image:'pnbp.png'},
{id:'ktt',name:'KTT & Keselamatan',category:'Keselamatan',desc:'Administrasi KTT dan keselamatan pertambangan.',image:'ktt.png'},
{id:'produksi',name:'Produksi & Penjualan',category:'Operasional',desc:'Pelaporan produksi dan penjualan.',image:'produksi.png'},
{id:'peta',name:'Peta & Perizinan',category:'Perizinan',desc:'Informasi spasial dan administrasi izin.',image:'peta.png'}
];
var $=function(s){return document.querySelector(s)},toastTimer;
function showToast(message){var t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(function(){t.classList.remove('show')},3400)}
function renderServices(q){q=(q||'').toLocaleLowerCase('id').trim();var shown=services.filter(function(s){return(s.name+' '+s.category+' '+s.desc).toLocaleLowerCase('id').indexOf(q)>-1});$('#service-list').innerHTML=shown.length?shown.map(function(s){return '<article class="service-card" style="--photo:url('+s.image+')"><span class="service-tag">'+s.category.toUpperCase()+'</span><h2>'+s.name+'</h2><p>'+s.desc+'</p><button data-toast="Alamat aplikasi resmi '+s.name+' akan dihubungkan setelah disiapkan pengelola.">Buka layanan ↗</button></article>'}).join(''):'<div class="empty"><b>Layanan tidak ditemukan</b><span>Coba kata kunci lain.</span></div>'}
function route(){var key=location.hash.slice(1)||'beranda';var map={beranda:'home-view',layanan:'layanan-view',informasi:'informasi-view',profil:'profil-view'};Object.keys(map).forEach(function(k){$('#'+map[k]).hidden=k!==key});document.querySelectorAll('[data-nav]').forEach(function(a){var active=a.dataset.nav===key;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});window.scrollTo(0,0)}
document.querySelectorAll('[data-route]').forEach(function(el){el.addEventListener('click',function(){location.hash=el.dataset.route})});document.querySelectorAll('[data-toast]').forEach(function(el){el.addEventListener('click',function(){showToast(el.dataset.toast)})});$('#notifications').onclick=function(){showToast('Belum ada notifikasi baru.')};$('#service-search').addEventListener('input',function(){renderServices(this.value)});window.addEventListener('hashchange',route);$('#service-list').addEventListener('click',function(e){var b=e.target.closest('[data-toast]');if(b)showToast(b.dataset.toast)});renderServices();route();
$('#open-calendar').onclick=function(){$('#calendar-dialog').showModal()};$('#close-calendar').onclick=function(){$('#calendar-dialog').close()};document.querySelectorAll('.calendar-day').forEach(function(day){day.addEventListener('click',function(){document.querySelectorAll('.calendar-day').forEach(function(x){x.classList.remove('selected')});day.classList.add('selected');showToast('Agenda '+day.textContent.trim()+' September akan tampil setelah kalender terhubung ke data resmi.')})});var initialDay=document.querySelector('.calendar-day.agenda-date');if(initialDay){document.querySelectorAll('.calendar-day.selected').forEach(function(x){x.classList.remove('selected')});initialDay.classList.add('selected')}
